### PR TITLE
ci: test also cmake  3.10

### PR DESCRIPTION
**Pull request by strk**
I can't build because the cmake version on ubuntu-18.04 is 3.10.2.
This PR is to check if it's possible to build there, given enough
time :)

### CODE REVIEW

**Comment by antanasbruzas** [comment]
According to [github help](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) ubuntu-latest is the same as ubuntu-18.04. Until they upgrade ubuntu-latest to 20.04 (which is [still not known when](https://github.com/actions/virtual-environments/issues/228#issuecomment-622256916)) it means that CI will run twice on the same environment. Or am I missing something? Maybe simply lowering required cmake version without changing CI would be fine?

**Comment by strk** [comment]
I reverted the change in OS matrix, but added a cmake matrix item, to test 3 cmake versions.
CI shows that 3.10 is NOT working due to:
>   CXX_STANDARD is set to invalid value '20'

Is there anything we can do to fix that, to improve support for older systems ? (my ubuntu 18.04 has cmake 3.10)

**Comment by strk** [comment]
For the record:
```
# apt-cache policy cmake
cmake:
  Installed: 3.10.2-1ubuntu2.18.04.1
  Candidate: 3.10.2-1ubuntu2.18.04.1
  Version table:
 *** 3.10.2-1ubuntu2.18.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.10.2-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by strk** [comment]
The [error](https://github.com/antanasbruzas/abNinjam/pull/5/checks?check_run_id=678277941#step:6:97) with cmake 3.10 is:
>   CXX_STANDARD is set to invalid value '20'

Would be nice to fix, but dunno when I'll have time to look at it - please keep this PR open if you don't plan to look at it yourself sooner

**Comment by antanasbruzas** [comment]
> The [error](https://github.com/antanasbruzas/abNinjam/pull/5/checks?check_run_id=678277941#step:6:97) with cmake 3.10 is:
> 
> > CXX_STANDARD is set to invalid value '20'
> 
> Would be nice to fix, but dunno when I'll have time to look at it - please keep this PR open if you don't plan to look at it yourself sooner

develop branch has a potential fix with https://github.com/antanasbruzas/abNinjam/commit/66cadb5ecf3bf9f88376cea8e9e5f4385f80f312

**Comment by strk** [comment]
I've rebased this PR against the "develop" branch. I saw your change only affected linux builds though, not Windows, so I guess the CI matrix should be changed accordingly, if things fail there...

**Comment by antanasbruzas** [comment]
> I've rebased this PR against the "develop" branch. I saw your change only affected linux builds though, not Windows, so I guess the CI matrix should be changed accordingly, if things fail there...

I know that windows build will fail with lower cmake versions but I don't have a windows machine to work on and it's a pain to develop for windows relying on github VM only (as you can see from commit history :))

**Comment by strk** [comment]
I've exluded windows with cmake < 3.15 from CI, linux and mac are still tested, and we're all happy :)

**Pull request merged**
